---
- name: "Generate Vlan Interface Config"
  loop: "{{vlan_interfaces}}"
  template:
    src: "../templates/vlan_interface.j2"
    dest: "./roles/vlan_interfaces/files/{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}-svi.xml"

- name: Configure Vlan Interfaces
  loop: "{{vlan_interfaces}}"
  netconf_config:
    datastore: running
    get_filter: <System xmlns="http://cisco.com/ns/yang/cisco-nx-os-device"></System>
    content: "{{ lookup('file', './roles/vlan_interfaces/files/{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}-svi.xml') }}"